### ISSUE TITLE
how can you get the result of EPE3d: 0.1136 for Flownet3d?

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [laoreja/HPLFlowNet#20]
The result in the original paper of flownet3d is 0.1694

**Comment by laoreja** [comment]
At the time when I worked on this paper, FlowNet3D is not open-sourced and details are missing (at that time their paper is on Arxiv without supp).
So I implemented the FlowNet3D myself in PyTorch, and reported the best result that I could achieve.

It could be the detailed settings, e.g., I cannot remember clearly whether they divided the point clouds into chunks for the result you are looking for. We did not chunk any point clouds as it would hurt performance.
It could possibly due to the fact that I trained the network for enough epochs.

Anyway, since they open-sourced their work, you should use their open-sourced code/model.
