### ISSUE TITLE
Problems when running against custom point-clouds with pre-trained models

### ISSUE THREAD

**Issue by GMNetto** [laoreja/HPLFlowNet#23]
Hi,

I got to run in the available KITTI dataset and it worked great. However, when I tried to run against a custom set of point clouds aIso from KITTI I had issues. The results are totally flawed. I used the provided config file, with no ground removal (since the dataset already had it done). The config  is attached. For the dataset folder, I followed the preprocessed KITTI example, so I had a folder `custom/KITTI_processed_occ_final/`. There each sequence in a folder with files `pc1.npy` and `pc2.npy`. 

Thank you

[hpl_config.txt](https://github.com/laoreja/HPLFlowNet/files/5407952/hpl_config.txt)

**Comment by laoreja** [comment]
I believe it’s because your processed point clouds do not have the similar distribution as the training data. Your point clouds may be very different from the ones I obtained, so simply using my preprocessing script will not work. 

Most likely, your point clouds have an opposite direction as mine, e.g., positive vs negative coordinates.

Visualizing the point clouds before sending them to training also helps.
