### ISSUE TITLE
Discrepancy in results of Flownet3d in HPLFlownet paper vs original flownet3d paper

### ISSUE THREAD

**Issue by HimangiM** [laoreja/HPLFlowNet#9]
Hi

Thank you posting the code. I noticed that the results for Flownet3d shown in Table 1 of your paper do not match the ones shown in Table 2 & Table 4 of the original Flownet3d paper. Can you please comment on this?

Thanks
Himangi

**Comment by laoreja** [comment]
When we submitted their paper, since flownet3d code & details is unavailable, we reimplemented a version based on their Arxiv submission at that time (mentioned in our paper). 

Besides, some known differences are:
- They sample 2048 points per point cloud while we sample 8192 points per point cloud.
- They used "Inference with random re-sampling" strategy while we do not use it as one of our focus is on speed and this strategy slows down inference speed.
- For KITTI, they used annotations for ground removal while we remove ground points by height since the ground removal annotations are not publicly available.
- On large KITTI scenes, they split the scene into multiple chunks while we do not have this preprocessing step.
